// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB81GTUS-kALkuvySvCXq_ckdseMakn9o',
    appId: '1:606402891932:web:a2f86172d02533f85e1d59',
    messagingSenderId: '606402891932',
    projectId: 'elite-6ebd5',
    authDomain: 'elite-6ebd5.firebaseapp.com',
    storageBucket: 'elite-6ebd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Uc7tMISz8ZdKjyZsa9qRjUlkFY4pDyI',
    appId: '1:606402891932:android:57663106ed6d2bb55e1d59',
    messagingSenderId: '606402891932',
    projectId: 'elite-6ebd5',
    storageBucket: 'elite-6ebd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsm8kIXz2sHx0O1WhZfHlhb2qqmrK-nrM',
    appId: '1:606402891932:ios:2e543dd88ef686445e1d59',
    messagingSenderId: '606402891932',
    projectId: 'elite-6ebd5',
    storageBucket: 'elite-6ebd5.appspot.com',
    iosClientId: '606402891932-4sbtf2hrcbvilaaeoah52b29srquvir7.apps.googleusercontent.com',
    iosBundleId: 'com.example.elite',
  );
}
